######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : peakfinding-workflow, Index = 0, Count = null
# SUBMIT FILE NAME : stage_worker_local_peakfinding-workflow_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/usr/local/Homebrew PATH=/Users/bianyiyang/jdk-17.0.2.jdk/Contents/Home/bin:/Users/bianyiyang/opt/anaconda3/bin:/Users/bianyiyang/opt/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/Homebrew/bin:/usr/local/Homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:.:/Users/bianyiyang/mongodb-macos-x86_64-5.0.8/bin:/usr/local/condor/bin:/usr/local/condor/sbin PYTHONPATH=/Users/bianyiyang/airflow/dags:/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm_matplotlib_backend:/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm_display CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=c9607984-6f75-4106-b20b-9312f5a7d24e PEGASUS_WF_LABEL=peakfinding-workflow PEGASUS_DAG_JOB_ID=stage_worker_local_peakfinding-workflow_0_local PEGASUS_SITE=local PEGASUS_BIN_DIR=/usr/local/Homebrew/bin _PEGASUS_CONNECT_STDIN=true"
arguments = "pegasus-kickstart  -n pegasus::transfer -N null -i - -R local  -L peakfinding-workflow -T 2022-06-08T22:33:56-04:00 pegasus-transfer  --threads 2 "
error = /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0003//00/00/stage_worker_local_peakfinding-workflow_0_local.err
executable = /usr/local/Homebrew/share/pegasus/sh/pegasus-lite-local.sh
input = /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0003//00/00/stage_worker_local_peakfinding-workflow_0_local.in
log = /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0003/peakfinding-workflow-0.log
notification = NEVER
output = /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0003//00/00/stage_worker_local_peakfinding-workflow_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 700
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "c9607984-6f75-4106-b20b-9312f5a7d24e"
+pegasus_wf_uuid = "c9607984-6f75-4106-b20b-9312f5a7d24e"
+pegasus_version = "5.0.2"
+pegasus_wf_name = "peakfinding-workflow-0"
+pegasus_wf_time = "20220608T223357-0400"
+pegasus_wf_xformation = "pegasus::transfer"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "stage_worker_local_peakfinding-workflow_0_local"
+pegasus_job_class = 2
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
