######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : peakfinding-workflow, Index = 0, Count = null
# SUBMIT FILE NAME : generate_source_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=30c3fd3d-e52d-4de4-9f31-031e2f862d03 PEGASUS_WF_LABEL=peakfinding-workflow PEGASUS_DAG_JOB_ID=generate_source_ID0000001 PEGASUS_SITE=condorpool"
+TransferOutput = ""
+WantIOProxy = True
error = /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0014//00/00/generate_source_ID0000001.err
executable = /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0014/00/00/generate_source_ID0000001.sh
initialdir = /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/wf-scratch/LOCAL/bianyiyang/pegasus/peakfinding-workflow/run0014
log = /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0014/peakfinding-workflow-0.log
notification = NEVER
output = /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0014//00/00/generate_source_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = generate_source,/Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0014/00/00/stage_in_remote_local_0_0.meta,/Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0014/pegasus-lite-common.sh,/Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0014/pegasus-worker-5.0.2-x86_64_rhel_7.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "30c3fd3d-e52d-4de4-9f31-031e2f862d03"
+pegasus_wf_uuid = "30c3fd3d-e52d-4de4-9f31-031e2f862d03"
+pegasus_version = "5.0.2"
+pegasus_wf_name = "peakfinding-workflow-0"
+pegasus_wf_time = "20220609T140319-0400"
+pegasus_wf_xformation = "generate_source"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "generate_source_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
