######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : peakfinding-workflow, Index = 0, Count = null
# SUBMIT FILE NAME : clean_up_local_level_3_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "PEGASUS_HOME=/usr/local/Homebrew PATH=/Users/bianyiyang/jdk-17.0.2.jdk/Contents/Home/bin:/Users/bianyiyang/opt/anaconda3/bin:/Users/bianyiyang/opt/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/Homebrew/bin:/usr/local/Homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:.:/Users/bianyiyang/mongodb-macos-x86_64-5.0.8/bin:/usr/local/condor/bin:/usr/local/condor/sbin PYTHONPATH=/Users/bianyiyang/airflow/dags:/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm_matplotlib_backend:/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm_display CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=57494d4a-0838-4487-a18e-c24b7fbf887c PEGASUS_WF_LABEL=peakfinding-workflow PEGASUS_DAG_JOB_ID=clean_up_local_level_3_0 PEGASUS_SITE=local"
arguments = " -n pegasus::cleanup -N null -i - -R local  -L peakfinding-workflow -T 2022-06-08T22:51:12-04:00 /usr/local/Homebrew/bin/pegasus-transfer "
error = /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0005//00/00/clean_up_local_level_3_0.err
executable = /usr/local/Homebrew/bin/pegasus-kickstart
input = /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0005//00/00/clean_up_local_level_3_0.in
log = /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0005/peakfinding-workflow-0.log
notification = NEVER
output = /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/bianyiyang/pegasus/peakfinding-workflow/run0005//00/00/clean_up_local_level_3_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "57494d4a-0838-4487-a18e-c24b7fbf887c"
+pegasus_wf_uuid = "57494d4a-0838-4487-a18e-c24b7fbf887c"
+pegasus_version = "5.0.2"
+pegasus_wf_name = "peakfinding-workflow-0"
+pegasus_wf_time = "20220608T225114-0400"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "clean_up_local_level_3_0"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
