x-pegasus:
  apiLang: python
  createdBy: bianyiyang
  createdOn: 06-17-22T00:46:11Z
pegasus: '5.0'
name: peakfinding-workflow
transformationCatalog:
  transformations:
  - name: generate_source
    sites:
    - name: local
      pfn: /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/generate_source.py
      type: stageable
  - name: generate_datacard
    sites:
    - name: local
      pfn: /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/generate_datacard.py
      type: stageable
  - name: generate_taskcard
    sites:
    - name: local
      pfn: /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/CRUX/to_cards/taskcard.py
      type: stageable
  - name: modelcard.py
    sites:
    - name: local
      pfn: /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/CRUX/to_cards/modelcard.py
      type: stageable
  - name: testcard.py
    sites:
    - name: local
      pfn: /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/CRUX/to_cards/testcard.py
      type: stageable
  - name: performance.py
    sites:
    - name: local
      pfn: /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/CRUX/to_cards/performance.py
      type: stageable
  - name: ranking.py
    sites:
    - name: local
      pfn: /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/CRUX/to_cards/ranking.py
      type: stageable
jobs:
- type: job
  name: generate_source
  id: ID0000001
  arguments:
  - -a
  - generate_soucrcecard
  - -T
  - '3'
  - -i
  - f.a
  - -o
  - f.b
  uses:
  - lfn: f.a
    type: input
  - lfn: f.b
    type: output
    stageOut: true
    registerReplica: true
- type: job
  name: generate_datacard
  id: ID0000002
  arguments:
  - -a
  - generate_datacard
  - -T
  - '3'
  - -i
  - f.b
  - -o
  - f.c
  uses:
  - lfn: f.c
    type: output
    stageOut: true
    registerReplica: true
  - lfn: f.b
    type: input
- type: job
  name: generate_taskcard
  id: ID0000003
  arguments:
  - -a
  - generate_taskcard
  - -T
  - '3'
  - -i
  - f.c
  - -o
  - f.d
  uses:
  - lfn: f.c
    type: input
  - lfn: f.d
    type: output
    stageOut: true
    registerReplica: true
- type: job
  name: modelcard.py
  id: ID0000004
  arguments:
  - -a
  - generate_modelcard
  - -T
  - '3'
  - -i
  - f.d
  - -o
  - f.e
  uses:
  - lfn: f.d
    type: input
  - lfn: f.e
    type: output
    stageOut: true
    registerReplica: true
- type: job
  name: testcard.py
  id: ID0000005
  arguments:
  - -a
  - generate_testcard
  - -T
  - '3'
  - -i
  - f.e
  - -o
  - f.f
  uses:
  - lfn: f.e
    type: input
  - lfn: f.f
    type: output
    stageOut: true
    registerReplica: true
- type: job
  name: performance.py
  id: ID0000006
  arguments:
  - -a
  - generate_performancecard
  - -T
  - '3'
  - -i
  - f.f
  - -o
  - f.g
  uses:
  - lfn: f.g
    type: output
    stageOut: true
    registerReplica: true
  - lfn: f.f
    type: input
- type: job
  name: ranking.py
  id: ID0000007
  arguments:
  - -a
  - generate_rankingcard
  - -T
  - '3'
  - -i
  - f.g
  - -o
  - f.h
  uses:
  - lfn: f.h
    type: output
    stageOut: true
    registerReplica: true
  - lfn: f.g
    type: input
jobDependencies:
- id: ID0000001
  children:
  - ID0000002
- id: ID0000002
  children:
  - ID0000003
- id: ID0000003
  children:
  - ID0000004
- id: ID0000004
  children:
  - ID0000005
- id: ID0000005
  children:
  - ID0000006
- id: ID0000006
  children:
  - ID0000007
